#!/bin/bash

TARGET="$1"
FEDORA_MAJOR_VERSION="$2"

set -xeu pipefail

kernel_version=$(curl -fsSL \
  https://raw.githubusercontent.com/ublue-os/bazzite/refs/heads/main/.github/workflows/build.yml | \
  grep -m1 'kernel_version:' | \
  awk '{gsub(/#.*/,""); print $2}' | \
  xargs)

if [ -z "$kernel_version" ]; then
  echo "Couldn't get Bazzite's pinned kernel version" >&2
  exit 1
fi

podman build . --target "$TARGET" --build-arg KERNEL_VERSION="$kernel_version"

