#!/bin/bash

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <target>
where target is one of:
  filotimo
  filotimo-nvidia"
    exit 1
fi

TARGET="$1"

set -xeu pipefail

kernel_version=$(curl -fsSL \
  https://raw.githubusercontent.com/ublue-os/bazzite/refs/heads/main/.github/workflows/build.yml | \
  grep -m1 'kernel_version:' | \
  awk '{gsub(/#.*/,""); print $2}' | \
  xargs)

if [ -z "$kernel_version" ]; then
  echo "Couldn't get Bazzite's pinned kernel version" >&2
  exit 1
fi

podman build . --build-arg IMAGE_NAME="$TARGET" --build-arg KERNEL_VERSION="$kernel_version"
