#!/usr/bin/bash

set -eo pipefail

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <target>
where target is one of:
  filotimo
  filotimo-nvidia"
    exit 1
fi

cd "$(git rev-parse --show-toplevel)"

curl -fSsO "https://copr.fedorainfracloud.org/coprs/tduck973564/filotimo-packages/repo/fedora-42/tduck973564-filotimo-packages-fedora-42.repo"
sed -i '/^priority=50$/s/50/1/' tduck973564-filotimo-packages-fedora-42.repo

image="ghcr.io/filotimo-project/$1:latest"

# Make temp space
TEMP_FLATPAK_INSTALL_DIR=$(mktemp -d -p "$(pwd)" flatpak.XXX)
# Get list of refs from directory
FLATPAK_REFS_DIR="$(pwd)"/flatpaks
FLATPAK_REFS_DIR_LIST=$(cat ${FLATPAK_REFS_DIR}/* | tr '\n' ' ' )
# Generate install script
cat << EOF > ${TEMP_FLATPAK_INSTALL_DIR}/script.sh
cat /temp_flatpak_install_dir/script.sh
mkdir -p /flatpak/flatpak /flatpak/triggers
mkdir /var/tmp || true
chmod -R 1777 /var/tmp
flatpak config --system --set languages "*"
flatpak remote-add --system flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install --system -y ${FLATPAK_REFS_DIR_LIST}
ostree refs --repo=\${FLATPAK_SYSTEM_DIR}/repo | grep '^deploy/' | grep -v 'org\.freedesktop\.Platform\.openh264' | sed 's/^deploy\///g' > /output/flatpaks-with-deps
EOF
sudo podman run --rm --privileged \
  --entrypoint bash \
  -e FLATPAK_SYSTEM_DIR=/flatpak/flatpak \
  -e FLATPAK_TRIGGERSDIR=/flatpak/triggers \
  --volume ${FLATPAK_REFS_DIR}:/output \
  --volume ${TEMP_FLATPAK_INSTALL_DIR}:/temp_flatpak_install_dir \
  ${image} /temp_flatpak_install_dir/script.sh
sudo podman rmi ${image}
rm -rf "$TEMP_FLATPAK_INSTALL_DIR"

sudo podman run --name=container-installer --replace --privileged \
--volume "$(pwd)":"/github/workspace/" \
ghcr.io/jasonn3/build-container-installer:v1.2.3 \
\
ADDITIONAL_TEMPLATES="/github/workspace/lorax_templates/remove_root_password_prompt.tmpl" \
ARCH="x86_64" \
ENABLE_CACHE_DNF="false" \
ENABLE_CACHE_SKOPEO="false" \
IMAGE_NAME="$1" \
IMAGE_REPO="ghcr.io/filotimo-project" \
IMAGE_TAG="latest" \
VERSION="42" \
VARIANT="kinoite" \
ISO_NAME="$1-latest.iso" \
SECURE_BOOT_KEY_URL="https://github.com/ublue-os/akmods/raw/main/certs/public_key.der" \
ENROLLMENT_PASSWORD="universalblue" \
FLATPAK_REMOTE_NAME="flathub" \
FLATPAK_REMOTE_URL="https://flathub.org/repo/flathub.flatpakrepo" \
FLATPAK_REMOTE_REFS_DIR="/github/workspace/flatpaks" \
ENABLE_FLATPAK_DEPENDENCIES="false" \
REPOS="/github/workspace/tduck973564-filotimo-packages-fedora-42.repo /etc/yum.repos.d/fedora.repo /etc/yum.repos.d/fedora-updates.repo"

rm -f ./tduck973564-filotimo-packages-fedora-42.repo

sudo podman cp container-installer:/build-container-installer/"$1"-latest.iso ./
sudo podman cp container-installer:/build-container-installer/"$1"-latest.iso-CHECKSUM ./
