#!/usr/bin/bash

set -ex

cd "$(git rev-parse --show-toplevel)"

image="ghcr.io/filotimo-project/filotimo:latest"
# Make temp space
TEMP_FLATPAK_INSTALL_DIR=$(mktemp -d -p . flatpak.XXX)
# Get list of refs from directory
FLATPAK_REFS_DIR=./flatpaks
FLATPAK_REFS_DIR_LIST=$(cat ${FLATPAK_REFS_DIR}/* | tr '\n' ' ' )

# Generate install script for Flatpaks
cat << EOF > "${TEMP_FLATPAK_INSTALL_DIR}"/script.sh
cat /temp_flatpak_install_dir/script.sh
mkdir -p /flatpak/flatpak /flatpak/triggers
mkdir /var/tmp || true
chmod -R 1777 /var/tmp
flatpak config --system --set languages "*"
flatpak remote-add --system flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install --system -y ${FLATPAK_REFS_DIR_LIST}
ostree refs --repo=\${FLATPAK_SYSTEM_DIR}/repo | grep '^deploy/' | grep -v 'org\.freedesktop\.Platform\.openh264' | sed 's/^deploy\///g' > /output/flatpaks_with_deps
EOF
sudo podman run --rm --privileged \
--entrypoint bash \
-e FLATPAK_SYSTEM_DIR=/flatpak/flatpak \
-e FLATPAK_TRIGGERSDIR=/flatpak/triggers \
--volume ${FLATPAK_REFS_DIR}:/output \
--volume "${TEMP_FLATPAK_INSTALL_DIR}":/temp_flatpak_install_dir \
${image} /temp_flatpak_install_dir/script.sh
sudo podman rmi ${image}

sudo podman run --name=container-installer --replace --privileged \
--volume "$(pwd)/flatpaks":"/build-container-installer/flatpaks" \
--volume "$(pwd)/lorax_templates":"/additional_lorax_templates" \
ghcr.io/jasonn3/build-container-installer:v1.2.2 \
ADDITIONAL_TEMPLATES="/additional_lorax_templates/remove_root_password_prompt.tmpl" \
ARCH="x86_64" \
ENABLE_CACHE_DNF="false" \
ENABLE_CACHE_SKOPEO="false" \
IMAGE_NAME="filotimo" \
IMAGE_REPO="ghcr.io/filotimo-project" \
IMAGE_TAG="latest" \
VERSION="41" \
VARIANT="kinoite" \
ISO_NAME="filotimo-latest-41.iso" \
SECURE_BOOT_KEY_URL="https://github.com/ublue-os/akmods/raw/main/certs/public_key.der" \
ENROLLMENT_PASSWORD="universalblue" \
FLATPAK_REMOTE_REFS_DIR="flatpaks" \
ENABLE_FLATPAK_DEPENDENCIES="false"
sudo podman cp container-installer:/build-container-installer/filotimo-latest-41.iso ./
sudo podman rmi ghcr.io/jasonn3/build-container-installer:v1.2.2
