#!/usr/bin/bash

# Copy global desktop file into user
mkdir -p $HOME/.local/share/applications
cp -r /usr/share/applications/boot-to-windows.desktop $HOME/.local/share/applications

# Look up the boot number for Windows in the EFI records
boot_number=$(echo $(efibootmgr) | grep -Po "(?<=Boot)\S{4}(?=( |\* )Windows)")

# Check that Windows EFI entry was found
if [ -z "$boot_number" ]; then
    sed -i 's/Hidden=true/Hidden=false/' $HOME/.local/share/applications/boot-to-windows.desktop
    exit 0
fi

sed -i 's/Hidden=true/Hidden=false/' $HOME/.local/share/applications/boot-to-windows.desktop
