#!/usr/bin/bash
if rpm-ostree status | grep -q 'openh264|mozilla-openh264|gstreamer1-plugin-openh264'; then
    echo "OpenH264 is already layered."
else
    echo "One or more OpenH264 packages were not layered, installing now..."
    dnf5 -y swap noopenh264 openh264
    dnf5 -y install mozilla-openh264 gstreamer1-plugin-openh264
    echo "Changes will take effect on next reboot."
fi
