#!/usr/bin/bash
set -eo pipefail

# thanks bazzite and bluefin:)

# Make sure to update this when new stuff is added/removed
SCRIPT_VER=2

SYS_ID="$(cat '/sys/devices/virtual/dmi/id/product_name')"
VEN_ID="$(cat '/sys/devices/virtual/dmi/id/chassis_vendor')"
CPU_VENDOR=$(grep "vendor_id" "/proc/cpuinfo" | uniq | awk -F": " '{ print $2 }')
CPU_MODEL=$(grep "model name" "/proc/cpuinfo" | uniq | awk -F": " '{ print $2 }')
DEVICE_ID="$SYS_ID $VEN_ID $CPU_MODEL $CPU_VENDOR"
KARGS=$(rpm-ostree kargs)
NEEDED_KARGS=()
NEEDS_REBOOT=0
NEEDS_MODULE_RELOAD=0
NEEDS_UDEV_RELOAD=0

SCRIPT_UPDATED=1
HARDWARE_CHANGED=1

# Check if this is a new version of the script
if [[ -f "/etc/ublue-os/.hardware-setup-script-version" ]]; then
  if [[ "$(cat '/etc/ublue-os/.hardware-setup-script-version')" == "$SCRIPT_VER" ]]; then
    echo "Script has not been updated."
    SCRIPT_UPDATED=0
  fi
fi
# Check if hardware has actually changed
if [[ -f "/etc/ublue-os/.device_id" ]]; then
  if [[ "$(cat '/etc/ublue-os/.device_id')" == "$DEVICE_ID" ]]; then
    echo "Hardware has not changed."
    HARDWARE_CHANGED=0
  fi
fi

if [[ "$SCRIPT_UPDATED" -eq 0 ]] && [[ "$HARDWARE_CHANGED" -eq 0 ]]; then
  echo "Exiting..."
  exit 0
fi


# Ensure full preempt is enabled
if [[ ! $KARGS =~ "preempt" ]]; then
  plymouth display-message --text="Configuring hardware - your system will reboot shortly..." || true
  echo "Adding needed kargs for full preemption"
  NEEDED_KARGS+=("--append-if-missing=preempt=full")
fi

# Fstab adjustments
if [[ ! -e /etc/ublue-os/.fstab_adjusted.flag && $(grep "compress=zstd" /etc/fstab) ]]; then
  plymouth display-message --text="Configuring hardware - your system will reboot shortly..." || true
  echo "Applying fstab param adjustments"
  for subvol in root home var; do
    sed -i "/subvol=$subvol/s/compress=zstd:1/noatime,lazytime,commit=120,discard=async,compress=zstd:1,space_cache=v2/" /etc/fstab
  done
  mkdir -p /etc/ublue-os/
  touch /etc/ublue-os/.fstab_adjusted.flag
  NEEDS_REBOOT=1
else
  echo "No fstab param adjustments needed"
fi

# Framework AMD fixes
if [[ ":Framework:" =~ ":$VEN_ID:" ]]; then
  if [[ "AuthenticAMD" == "$CPU_VENDOR" ]]; then
    # Load Ryzen SMU on AMD Framework Laptops
    if ! [[ -f "/etc/modules-load.d/ryzen_smu.conf" ]]; then
      NEEDS_MODULE_RELOAD=1
      plymouth display-message --text="Configuring hardware..." || true
      mkdir -p "/etc/modules-load.d"
      printf "# Load ryzen_smu driver upon startup\nryzen_smu\n" >> "/etc/modules-load.d/ryzen_smu.conf"
    fi
    # Framework 13 AMD fixes
    if [[ $SYS_ID == "Laptop ("* ]]; then
      if [[ ! -f /etc/modprobe.d/alsa.conf ]]; then
        NEEDS_MODULE_RELOAD=1
        plymouth display-message --text="Configuring hardware..." || true
        echo 'Fixing 3.5mm jack'
        echo "options snd-hda-intel index=1,0 model=auto,dell-headset-multi" > /etc/modprobe.d/alsa.conf
        echo 0 > /sys/module/snd_hda_intel/parameters/power_save
      fi
      if [[ ! -f /etc/udev/rules.d/20-suspend-fixes.rules ]]; then
        NEEDS_UDEV_RELOAD=1
        plymouth display-message --text="Configuring hardware..." || true
        echo 'Fixing suspend issue'
        echo "ACTION==\"add\", SUBSYSTEM==\"serio\", DRIVERS==\"atkbd\", ATTR{power/wakeup}=\"disabled\"" > /etc/udev/rules.d/20-suspend-fixes.rules
      fi
    fi
  fi
fi
if [[ ! ":Framework:" =~ ":$VEN_ID:" ]]; then
  if [[ ! "AuthenticAMD" == "$CPU_VENDOR" ]]; then
    if [[ -f "/etc/modules-load.d/ryzen_smu.conf" ]]; then
      plymouth display-message --text="Configuring hardware..." || true
      rm -rf "/etc/modules-load.d/ryzen_smu.conf"
    fi
  fi
  if [[ -f "/etc/udev/rules.d/20-suspend-fixes.rules" ]]; then
    NEEDS_UDEV_RELOAD=1
    plymouth display-message --text="Configuring hardware..." || true
    rm -rf "/etc/udev/rules.d/20-suspend-fixes.rules"
  fi
  NEEDS_MODULE_RELOAD=1
  plymouth display-message --text="Configuring hardware..." || true
  sed -i '/^options snd-hda-intel index=1,0 model=auto,dell-headset-multi$/d' /etc/modprobe.d/alsa.conf
fi


# Other Framework fixes
if [[ ":Framework:" =~ ":$VEN_ID:" ]]; then
  if [[ "AuthenticAMD" == "$CPU_VENDOR" ]]; then
    if [[ ! $KARGS =~ "iomem" ]]; then
      plymouth display-message --text="Configuring hardware - your system will reboot shortly..." || true
      echo "AMD Framework Laptop detected, adding needed kargs for ryzenadj"
      NEEDED_KARGS+=("--append-if-missing=iomem=relaxed")
    fi
  elif [[ "GenuineIntel" == "$CPU_VENDOR" ]]; then
    if [[ ! $KARGS =~ "hid_sensor_hub" ]]; then
      plymouth display-message --text="Configuring hardware - your system will reboot shortly..." || true
      echo "Intel Framework Laptop detected, applying needed keyboard fix"
      NEEDED_KARGS+=("--append-if-missing=module_blacklist=hid_sensor_hub")
    fi
  fi
fi
if [[ ! ":Framework:" =~ ":$VEN_ID:" ]]; then
  if [[ $KARGS =~ "iomem=relaxed" ]]; then
    plymouth display-message --text="Configuring hardware - your system will reboot shortly..." || true
    NEEDED_KARGS+=("--delete-if-present=iomem=relaxed")
  fi
  if [[ $KARGS =~ "module_blacklist=hid_sensor_hub" ]]; then
    plymouth display-message --text="Configuring hardware - your system will reboot shortly..." || true
    NEEDED_KARGS+=("--delete-if-present=module_blacklist=hid_sensor_hub")
  fi
fi

# Surface fixes
if [[ ":Microsoft:" =~ ":$VEN_ID:" ]]; then
  if ! [[ -f "/etc/modules-load.d/surface.conf" ]]; then
    NEEDS_MODULE_RELOAD=1
    plymouth display-message --text="Configuring hardware..." || true
    sed 's/^ *//' > "/etc/modules-load.d/surface.conf" << EOF
      # Add modules necessary for Disk Encryption via keyboard
      surface_aggregator
      surface_aggregator_registry
      surface_aggregator_hub
      surface_hid_core
      8250_dw

      # Surface Laptop 3/Surface Book 3 and later
      surface_hid
      surface_kbd

EOF
    if [[ "AuthenticAMD" == "$CPU_VENDOR" ]]; then
      printf "# Support GPIO pins on AMD Surfaces\npinctrl_amd\n" >> "/etc/modules-load.d/surface.conf"
    elif [[ "GenuineIntel" == "$CPU_VENDOR" ]]; then
      sed 's/^ *//' >> "/etc/modules-load.d/surface.conf" << EOF
        # Support LPSS on Intel Surfaces
        intel_lpss
        intel_lpss_pci

        # Support GPIO pins on Intel Surfaces
        # Surface Book 2
        pinctrl_sunrisepoint

        # For Surface Laptop 3/Surface Book 3
        pinctrl_icelake

        # For Surface Laptop 4/Surface Laptop Studio
        pinctrl_tigerlake

        # For Surface Pro 9/Surface Laptop 5
        pinctrl_alderlake

        # For Surface Pro 10/Surface Laptop 6
        pinctrl_meteorlake
EOF
    fi
  fi
fi

if ! [[ ":Microsoft:" =~ ":$VEN_ID:" ]]; then
  if [[ -f "/etc/modules-load.d/surface.conf" ]]; then
    plymouth display-message --text="Configuring hardware..." || true
    rm -rf /etc/modules-load.d/surface.conf
    NEEDS_MODULE_RELOAD=1
  fi
fi

# NVIDIA sometimes doesn't like sleep
if nvidia-smi &>/dev/null && [[ ! "$KARGS" =~ "mem_sleep_default" ]]; then
  plymouth display-message --text="Configuring hardware - your system will reboot shortly..." || true
  NEEDED_KARGS+=("--append-if-missing=mem_sleep_default=s2idle")
fi
if ! nvidia-smi &>/dev/null && [[ "$KARGS" =~ "mem_sleep_default" ]]; then
  plymouth display-message --text="Configuring hardware - your system will reboot shortly..." || true
  NEEDED_KARGS+=("--delete-if-present=mem_sleep_default=s2idle")
fi

# Fix from Bluefin
if nvidia-smi &>/dev/null && [[ ! "$KARGS" =~ "initcall_blacklist=simpledrm_platform_driver_init" ]]; then
  plymouth display-message --text="Configuring hardware - your system will reboot shortly..." || true
  NEEDED_KARGS+=("--append-if-missing=initcall_blacklist=simpledrm_platform_driver_init")
fi
if ! nvidia-smi &>/dev/null && [[ "$KARGS" =~ "initcall_blacklist=simpledrm_platform_driver_init" ]]; then
  plymouth display-message --text="Configuring hardware - your system will reboot shortly..." || true
  NEEDED_KARGS+=("--delete-if-present=initcall_blacklist=simpledrm_platform_driver_init")
fi

# Apply karg changes
if [[ -n "$NEEDED_KARGS" ]]; then
  echo "Found needed karg changes, applying the following: ${NEEDED_KARGS[*]}"
  rpm-ostree kargs ${NEEDED_KARGS[*]} || exit 1
  NEEDS_REBOOT=1
else
  echo "No karg changes needed"
fi

# Regenerate device ID, set script ver
echo "$DEVICE_ID" > "/etc/ublue-os/.device_id"
echo "$SCRIPT_VER" > "/etc/ublue-os/.hardware-setup-script-version"

if [[ "$NEEDS_REBOOT" -eq 1 ]]; then
  systemctl reboot
fi

if [[ "$NEEDS_MODULE_RELOAD" -eq 1 ]]; then
  systemctl restart systemd-modules-load.service
fi

if [[ "$NEEDS_UDEV_RELOAD" -eq 1 ]]; then
  systemctl restart systemd-udevd.service
fi

plymouth hide-message --text="Configuring hardware..." || true
