name: Build Filotimo ISO
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '00 12 * * 2'
  workflow_dispatch:
  workflow_call:
  workflow_run:
    workflows:
      - Build Filotimo OCI Image
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-iso
  cancel-in-progress: true

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build ISO
        id: build
        shell: bash
        run: |
          set -eo pipefail
          cd "${{ github.workspace }}"

          ./build-iso filotimo

          iso_name=filotimo-latest-41
          echo "iso_name=filotimo-latest-41" >> $GITHUB_OUTPUT

          mkdir -p ISO
          mv "$iso_name".iso ISO/
          mv "$iso_name".iso-CHECKSUM ISO/

          echo "iso_path=$(readlink -f ./ISO/$iso_name.iso)" >> $GITHUB_OUTPUT

      - name: Upload ISO as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.iso_name }}
          path: |
            ${{ steps.build.outputs.iso_path }}
            ${{ steps.build.outputs.iso_path }}-CHECKSUM
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
          overwrite: true

      - name: Set up SCP
        run: |
          mkdir -v -m 700 $HOME/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} > $HOME/.ssh/known_hosts
          echo "${{ secrets.KEY }}" > $HOME/.ssh/id_rsa            
          chmod 400 $HOME/.ssh/id_rsa
        
      - name: Upload ISO to host
        run: |
          scp -P ${{ secrets.PORT }} ${{ steps.build.outputs.iso_path }} ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/download.filotimoproject.org/
          scp -P ${{ secrets.PORT }} ${{ steps.build.outputs.iso_path }}-CHECKSUM ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/download.filotimoproject.org/